version: '2.1'

services:
  pcq-backend:
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: hmctspublic.azurecr.io/spring-boot/template
    environment:
      # these environment variables are used by java-logging library
      - ROOT_APPENDER
      - JSON_CONSOLE_PRETTY_PRINT
      - ROOT_LOGGING_LEVEL
      - REFORM_SERVICE_TYPE
      - REFORM_SERVICE_NAME
      - REFORM_TEAM
      - REFORM_ENVIRONMENT
      - LOGBACK_DATE_FORMAT
      - LOGBACK_REQUIRE_THREAD
      - LOGBACK_REQUIRE_ALERT_LEVEL=false
      - LOGBACK_REQUIRE_ERROR_CODE=false
    ports:
      - $SERVER_PORT:$SERVER_PORT

  pcq-backend-database:
    build: docker/database
    healthcheck:
      interval: 10s
      timeout: 10s
      retries: 10
    environment:
      PCQ_DB: ${PCQ_DB}
      PCQ_DB_USERNAME: ${PCQ_DB_USERNAME}
      PCQ_DB_PASSWORD: ${PCQ_DB_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5050:5432
    volumes:
      - pcq-backend-database-data:/var/lib/postgresql/data

volumes:
  pcq-backend-database-data:
