server:
  port: 4550

management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus

#Application specific properties
api-error-messages:
  bad_request: Invalid Request
  created: Successfully created
  accepted: Success
  internal_error: Unknown error occurred
api-required-header-keys:
  co-relationid: X-Correlation-Id
api-schema-file:
  submitanswer-schema: submitAnswersSchema.json
api-version-number: 1


#If you use a database then uncomment below lines and update db properties accordingly

spring:
  application:
    name: Protected Characteristics Questions
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${PCQ_DB_HOST:localhost}:${PCQ_DB_PORT:5432}/${PCQ_DB:pcq}${PCQ_DB_CONN_OPTIONS:}
    username: ${PCQ_DB_USERNAME:pcquser}
    password: ${PCQ_DB_PASSWORD:pcqpass}
    properties:
      charSet: UTF-8
    hikari:
      minimumIdle: 2
      maximumPoolSize: 10
      idleTimeout: 10000
      poolName: PCQHikariCP
      maxLifetime: 7200000
      connectionTimeout: 30000
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            # silence the 'wall-of-text' - unnecessary exception throw about blob types
            non_contextual_creation: true

flyway:
  noop:
    strategy: "false"
