server:
  port: 4550

management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus

#Application specific properties
api-error-messages:
  bad_request: Invalid Request
  created: Successfully created
  updated: Successfully updated
  accepted: Success
  internal_error: Unknown error occurred
api-required-header-keys:
  co-relationid: X-Correlation-Id
api-schema-file:
    submitanswer-schema: JsonSchema/submitAnswersSchema.json
api-version-number: 1
api-config-params:
  number_of_days_limit: 90

#Application specific unit test properties
unit-test:
  api-urls:
    submit_answer: /pcq/backend/submitAnswers
security:
  jwt:
    header: Authorization
    prefix: Bearer

#If you use a database then uncomment below lines and update db properties accordingly
spring:
  application:
    name: Spring Boot Template
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:postgresql://localhost/pcq
#    properties:
#      charSet: UTF-8
#    hikari:
#      minimumIdle: 2
#      maximumPoolSize: 10
#      idleTimeout: 10000
#      poolName: {to-be-defined}HikariCP
#      maxLifetime: 7200000
#      connectionTimeout: 30000
  jpa:
#    properties:
#      hibernate:
#        jdbc:
#          lob:
#            # silence the 'wall-of-text' - unnecessary exception throw about blob types
#            non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  flyway:
    locations: classpath:db/migration

flyway:
  noop:
    strategy: "false"
