
spring:
  application:
    name: Protected Characteristics Questions Functional Tests
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:postgresql:///${PCQ_DB:pcq}?TC_INITFUNCTION=org.testcontainers.jdbc.JDBCDriverTest::pcqInitFunction
    properties:
      charSet: UTF-8
    hibernate:
      dialect: PostgreSQLDialect
      ddl-auto: create-drop
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      dialect: PostgreSQLDialect
      ddl-auto: none



